#!/usr/bin/env bash
#
# A script to run a jailed language model in Nix (or Docker).
#
# Usage:
#
# $ ./jaillm [jaillm.nix]

set -eou pipefail

filepath="jaillm.nix"
if [ "$#" -ge 1 ]; then
    filepath="$1"
fi

# If not a file, fail
if [ ! -f "$filepath" ]; then
    echo "Error: File '$filepath' not found."
    exit 1
fi

export JAILLM_FLAKE="github:myme/jaillm"
export JAILLM_NIX="$(readlink -f "$filepath")"

nix run --impure --expr '
let
  jaillm = builtins.getFlake (builtins.getEnv "JAILLM_FLAKE");
  config = import (builtins.getEnv "JAILLM_NIX");
in
  jaillm.lib.build (import <nixpkgs>) config
'
